---
# Arch Linux-specific font variables

# Font installation paths
font_install_path: "{{ ansible_user_dir }}/.local/share/fonts"
system_font_path: "/usr/share/fonts"

# Font cache command
font_cache_command: "fc-cache -fv"

# Dependencies
font_dependencies:
  - unzip
  - fontconfig

# Arch Linux-specific font management
archlinux_font_config:
  user_fonts_dir: "{{ ansible_user_dir }}/.local/share/fonts"
  system_fonts_dir: "/usr/share/fonts"
  font_config_dir: "{{ ansible_user_dir }}/.config/fontconfig"
  
# Font validation commands
font_validation_commands:
  list_fonts: "fc-list"
  check_iosevka: "fc-list | grep -i iosevka"
  font_info: "fc-query"

# Pacman font packages (alternative installation method)
pacman_font_packages:
  - ttf-iosevka-nerd
  - ttf-jetbrains-mono-nerd
  - ttf-fira-code
  - ttf-hack-nerd

# AUR font packages
aur_font_packages:
  - nerd-fonts-iosevka
  - nerd-fonts-jetbrains-mono
  - nerd-fonts-fira-code
  - nerd-fonts-hack

# Font configuration
fontconfig_settings:
  enable_antialiasing: true
  enable_hinting: true
  hinting_style: "slight"
  subpixel_rendering: "rgb"
