---
# Arch Linux-specific variables for development environment setup
# Equivalent to macOS macsible.yaml functionality for Arch Linux

# Software inventory - tracks all managed software
pacman_packages:
  - base-devel
  - git
  - curl
  - wget
  - vim
  - neovim
  - tmux
  - zsh
  - starship
  - alacritty
  - firefox
  - docker
  - docker-compose
  - python
  - python-pip
  - nodejs
  - npm
  - go
  - rust
  - rustup
  - ripgrep
  - fd
  - bat
  - exa
  - fzf
  - ranger
  - htop
  - tree
  - unzip
  - zip
  - jq
  - yq
  - zoxide

# AUR packages (requires AUR helper)
aur_packages:
  - visual-studio-code-bin
  - google-chrome
  - discord
  - slack-desktop
  - notion-app
  - postman-bin
  - zellij
  - lazygit
  - bottom
  - obsidian
  - figma-linux
  - zoom

# Development packages - Enhanced with comprehensive toolchain
dev_packages:
  - gcc
  - clang
  - llvm
  - cmake
  - make
  - ninja
  - meson
  - autoconf
  - automake
  - libtool
  - pkg-config
  - openssl
  - sqlite
  - postgresql
  - redis
  - mongodb-bin

# Cross-platform assemblers and low-level tools
assembler_packages:
  - nasm
  - yasm
  - gdb
  - lldb
  - valgrind
  - strace
  - perf
  - binutils
  - objdump

# Build systems and development utilities
build_tools:
  - bazel
  - ccache
  - distcc
  - sccache
  - shellcheck
  - shfmt

# Language toolchains
language_packages:
  - zig
  - crystal
  - nim
  - dmd  # D language compiler
  - ldc   # LLVM D compiler

# Cross-compilation toolchains (AUR)
cross_compilation_aur:
  - arm-linux-gnueabihf-gcc
  - aarch64-linux-gnu-gcc
  - mingw-w64-gcc

# Window manager packages
wm_packages:
  - i3-wm
  - i3status
  - i3lock
  - sway
  - waybar
  - wofi
  - rofi
  - dmenu
  - polybar
  - picom
  - dunst
  - feh
  - grim
  - slurp
  - wl-clipboard

# Fonts
font_packages:
  - ttf-jetbrains-mono
  - ttf-font-awesome
  - noto-fonts
  - noto-fonts-emoji
  - powerline-fonts
  - ttf-hack

# System utilities
system_packages:
  - networkmanager
  - bluez
  - bluez-utils
  - pulseaudio
  - pulseaudio-bluetooth
  - pavucontrol
  - brightnessctl
  - acpi
  - upower

# NPM global packages (same as macOS for consistency)
npm_global_packages:
  - "@angular/cli"
  - "create-react-app"
  - "typescript"
  - "ts-node"
  - "nodemon"
  - "pm2"
  - "yarn"
  - "pnpm"
  - "eslint"
  - "prettier"
  - "http-server"
  - "live-server"
  - "@modelcontextprotocol/server-brave-search"
  - "@modelcontextprotocol/server-puppeteer"
  - "firecrawl-mcp"

# ZSH and Oh My Zsh configuration
zsh_packages:
  - zsh
  - fzf

# Oh My Zsh plugins to install via git clone
oh_my_zsh_plugins:
  - name: zsh-autosuggestions
    repo: https://github.com/zsh-users/zsh-autosuggestions
  - name: zsh-fzf-history-search
    repo: https://github.com/joshskidmore/zsh-fzf-history-search
  - name: zsh-syntax-highlighting
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
  - name: zsh-history-substring-search
    repo: https://github.com/zsh-users/zsh-history-substring-search

# FZF configuration
fzf_install_method: "pacman"  # pacman, git, or binary

# Python packages
python_packages:
  - "pynvim"
  - "black"
  - "isort"
  - "flake8"
  - "mypy"
  - "pytest"
  - "requests"
  - "beautifulsoup4"
  - "pandas"
  - "numpy"

# Rust packages (cargo) - Enhanced with development tools
cargo_packages:
  - "lsd"
  - "zellij"
  - "starship"
  - "ripgrep"
  - "fd-find"
  - "bat"
  - "exa"
  - "bottom"
  - "tokei"
  - "hyperfine"
  - "zoxide"
  - "cargo-edit"
  - "cargo-watch"
  - "cargo-expand"
  - "cargo-audit"
  - "cargo-outdated"
  - "cargo-tree"

# Go packages (go install) - Essential Go development tools
go_packages:
  - "github.com/golangci/golangci-lint/cmd/golangci-lint@latest"
  - "golang.org/x/tools/cmd/goimports@latest"
  - "golang.org/x/tools/cmd/godoc@latest"
  - "github.com/go-delve/delve/cmd/dlv@latest"
  - "honnef.co/go/tools/cmd/staticcheck@latest"
  - "golang.org/x/tools/gopls@latest"
  - "github.com/fatih/gomodifytags@latest"
  - "github.com/josharian/impl@latest"

# Python development packages (pipx)
python_dev_packages:
  - "black"
  - "flake8"
  - "mypy"
  - "pytest"
  - "poetry"
  - "pipenv"
  - "virtualenv"
  - "cookiecutter"
  - "pre-commit"
  - "ansible-lint"
  - "community-ansible-dev-tools"

# Node.js development tools (global npm packages)
node_dev_packages:
  - "@typescript-eslint/eslint-plugin"
  - "@typescript-eslint/parser"
  - "webpack"
  - "webpack-cli"
  - "vite"
  - "esbuild"
  - "rollup"
  - "parcel"
  - "jest"
  - "mocha"
  - "cypress"

# AUR helper preference
aur_helper: "yay"

# Services to enable
systemd_services:
  - "NetworkManager"
  - "bluetooth"
  - "docker"

# Development directories to create
development_directories:
  - "{{ ansible_user_dir }}/dev"
  - "{{ ansible_user_dir }}/projects"
  - "{{ ansible_user_dir }}/src"
  - "{{ ansible_user_dir }}/.local/bin"

# Environment variables
arch_environment_vars:
  - name: "EDITOR"
    value: "nvim"
  - name: "BROWSER"
    value: "firefox"
  - name: "TERMINAL"
    value: "alacritty"
  - name: "PATH"
    value: "{{ ansible_user_dir }}/.local/bin:{{ ansible_user_dir }}/.cargo/bin:{{ ansible_user_dir }}/go/bin:$PATH"
