---
# Ansible Collections
collections:
  # Core collections for cross-platform support
  - name: ansible.posix
    version: ">=1.5.0"
  
  - name: community.general
    version: ">=8.0.0"
  
  # Windows support
  - name: ansible.windows
    version: ">=1.14.0"
  
  - name: community.windows
    version: ">=1.13.0"
  
  # macOS support
  - name: community.crypto
    version: ">=2.15.0"
  
  # Package management
  - name: chocolatey.chocolatey
    version: ">=1.5.0"
  
  # Docker and containerization
  - name: community.docker
    version: ">=3.4.0"
  


# External Roles (if needed)
roles:
  # Example: External role for advanced dotfiles management
  # - name: geerlingguy.dotfiles
  #   version: "2.0.0"
  
  # Example: External role for development tools
  # - name: geerlingguy.homebrew
  #   version: "4.2.0"