---
# Main site playbook for restructured dotfiles
- name: Cross-Platform Development Environment Setup
  hosts: localhost
  gather_facts: yes
  become: no
  vars:
    current_profile: "{{ profile | default('developer') }}"
    
  pre_tasks:
    - name: Display configuration banner
      debug:
        msg: |
          ╔══════════════════════════════════════════════════════════════╗
          ║                    DOTFILES CONFIGURATION                   ║
          ║              Cross-Platform Development Setup               ║
          ╚══════════════════════════════════════════════════════════════╝
          
          🖥️  Host: {{ inventory_hostname }}
          🐧  OS: {{ ansible_distribution }} {{ ansible_distribution_version }}
          🏗️  Architecture: {{ ansible_architecture }}
          👤  Profile: {{ current_profile }}
          ⏰  Timestamp: {{ ansible_date_time.iso8601 }}

  tasks:
    - name: Phase 1 - Directory structure created
      debug:
        msg: |
          ✅ Phase 1 completed successfully!
          Directory structure is now dotsible-compatible.
          
          Created directories:
          - roles/ (applications, platform_specific, profiles)
          - group_vars/ and inventories/
          - templates/ and files/dotfiles/
          - tests/ and docs/
          
          Next: Execute Phase 2 (Configuration Migration)
