---
# Test playbook to validate the fixed GNU Stow dotfiles syntax
- name: Test Fixed GNU Stow Dotfiles Syntax
  hosts: localhost
  gather_facts: yes
  vars:
    dotfiles:
      enabled: true
      local_path: "{{ playbook_dir }}/files/dotfiles"
      backup_existing: true
      backup_directory: "{{ ansible_user_dir }}/.dotsible/backups"
      symlink_strategy: "force"
      create_directories: true
      cleanup_broken_links: true

  tasks:
    - name: "🧪 TEST: Fixed GNU Stow Syntax"
      debug:
        msg: "Testing the fixed GNU Stow dotfiles implementation"
      tags: ['test']

    - name: Include the fixed dotfiles role
      include_role:
        name: dotfiles
      tags: ['dotfiles']
