---
# Test playbook to validate the GNU Stow dotfiles fix
- name: Test GNU Stow Dotfiles Implementation
  hosts: localhost
  gather_facts: yes
  vars:
    dotfiles:
      enabled: true
      local_path: "{{ playbook_dir }}/files/dotfiles"
      backup_existing: true
      backup_directory: "{{ ansible_user_dir }}/.dotsible/backups"
      symlink_strategy: "force"
      create_directories: true
      cleanup_broken_links: true

  tasks:
    - name: "🧪 TEST: GNU Stow Dotfiles Fix"
      debug:
        msg: "Testing the enhanced GNU Stow dotfiles implementation"
      tags: ['test']

    - name: Include the enhanced dotfiles role
      include_role:
        name: dotfiles
      tags: ['dotfiles']

    - name: "🔍 Verify directory structure is GNU Stow compatible"
      shell: |
        echo "📂 Checking dotfiles structure for GNU Stow compatibility..."
        cd "{{ playbook_dir }}/files/dotfiles"
        
        echo ""
        echo "Available applications:"
        ls -1 | grep -v "^\." | head -10
        
        echo ""
        echo "🔍 Checking nvim structure:"
        if [ -d "nvim" ]; then
          find nvim -type f | head -3
          echo "✅ nvim structure: $(find nvim -name "*.lua" | wc -l) Lua files found"
        else
          echo "❌ nvim directory not found"
        fi
        
        echo ""
        echo "🔍 Checking zsh structure:"
        if [ -f "zsh/.zshrc" ]; then
          echo "✅ zsh/.zshrc found ($(wc -l < zsh/.zshrc) lines)"
        else
          echo "❌ zsh/.zshrc not found"
        fi
        
        echo ""
        echo "🔍 Expected symlink targets:"
        echo "nvim/.config/nvim/ → ~/.config/nvim/"
        echo "zsh/.zshrc → ~/.zshrc"
        
        echo ""
        echo "📋 GNU Stow commands that would be executed:"
        echo "cd {{ playbook_dir }}/files/dotfiles"
        echo "stow --target=$HOME nvim"
        echo "stow --target=$HOME zsh"
      register: structure_check
      changed_when: false
      tags: ['test', 'structure']

    - name: Display structure check results
      debug:
        msg: "{{ structure_check.stdout_lines }}"
      tags: ['test', 'structure']

    - name: "📋 Summary of the fix"
      debug:
        msg: |
          🔧 GNU Stow Dotfiles Fix Summary:
          
          ✅ FIXED ISSUES:
          • Working directory: stow commands now execute from {{ playbook_dir }}/files/dotfiles
          • Proper GNU Stow integration: replaced copy tasks with stow commands
          • Idempotent deployment: checks existing symlinks before creating new ones
          • Conflict resolution: backup existing files before stow deployment
          • Status reporting: clear indicators (✅ DEPLOYED, ⏭️ SKIPPED, ❌ FAILED)
          
          🔗 CORRECT SYMLINK BEHAVIOR:
          • nvim/.config/nvim/ → ~/.config/nvim/ (not ~/.config/nvim/.config/nvim/)
          • zsh/.zshrc → ~/.zshrc
          • tmux/.tmux.conf → ~/.tmux.conf
          
          📦 REQUIREMENTS:
          • GNU Stow must be installed (brew install stow / apt install stow)
          • Dotfiles must follow GNU Stow directory structure (✅ verified)
          
          🚀 NEXT STEPS:
          1. Install GNU Stow on the system
          2. Run: ansible-playbook playbooks/workstation.yml --tags dotfiles
          3. Verify symlinks: ls -la ~/.config/nvim ~/.zshrc
      tags: ['test', 'summary']
