---
# ZSH application role - Cross-platform shell setup with Oh My Zsh
# This role installs and configures ZSH with Oh My Zsh across different operating systems

- name: Include OS-specific variables
  include_vars: "{{ ansible_os_family | lower }}.yml"
  failed_when: false
  tags: ['zsh', 'variables']

- name: Include profile-specific variables
  include_vars: "profile_{{ profile | default('minimal') }}.yml"
  failed_when: false
  tags: ['zsh', 'variables', 'profile']

- name: Display ZSH configuration info
  debug:
    msg: |
      Configuring ZSH for {{ inventory_hostname }}
      OS Family: {{ ansible_os_family }}
      Profile: {{ profile | default('minimal') }}
      Theme: {{ zsh_theme | default('robbyrussell') }}
      Oh My Zsh: {{ 'Enabled' if zsh_oh_my_zsh_enabled else 'Disabled' }}
  tags: ['zsh', 'info']

- name: Install ZSH
  include_tasks: install_zsh.yml
  tags: ['zsh', 'install']

- name: Install Oh My Zsh
  include_tasks: install_oh_my_zsh.yml
  when: zsh_oh_my_zsh_enabled | default(true)
  tags: ['zsh', 'oh-my-zsh']

- name: Configure ZSH settings
  include_tasks: configure_zsh.yml
  tags: ['zsh', 'config']

- name: Setup ZSH plugins
  include_tasks: setup_plugins.yml
  when: zsh_plugins is defined and zsh_plugins | length > 0
  tags: ['zsh', 'plugins']

- name: Setup FZF integration
  include_tasks: setup_fzf_integration.yml
  when: zsh_fzf_enabled | default(true)
  tags: ['zsh', 'fzf']

- name: Setup ZSH theme
  include_tasks: setup_theme.yml
  tags: ['zsh', 'theme']

- name: Configure ZSH aliases
  include_tasks: setup_aliases.yml
  tags: ['zsh', 'aliases']

- name: Setup ZSH functions
  include_tasks: setup_functions.yml
  when: zsh_custom_functions_enabled | default(false)
  tags: ['zsh', 'functions']

- name: Configure ZSH environment
  include_tasks: setup_environment.yml
  tags: ['zsh', 'environment']

- name: Set ZSH as default shell
  include_tasks: set_default_shell.yml
  when: zsh_set_as_default | default(true)
  tags: ['zsh', 'default']

- name: Verify ZSH installation
  include_tasks: verify_zsh.yml
  tags: ['zsh', 'verify']

- name: Create ZSH configuration backup
  include_tasks: backup_config.yml
  when: zsh_backup_enabled | default(true)
  tags: ['zsh', 'backup']
