---
# Font management role metadata

galaxy_info:
  author: Dotsible Project
  description: Cross-platform font management and installation
  company: Dotsible
  license: MIT
  min_ansible_version: 2.9
  
  platforms:
    - name: Darwin
      versions:
        - all
    - name: Windows
      versions:
        - all
    - name: Archlinux
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all

  galaxy_tags:
    - fonts
    - nerd-fonts
    - iosevka
    - development
    - cross-platform

dependencies: []
