
# Environment variables
#env = { TERM = "alacritty" }

# Window properties
[window]
opacity = 0.8

# Startup mode
#startup_mode = "Windowed"

# Window title
#title = "Alacritty"

# Font configuration
[font]
normal = { family = "Iosevka Nerd Font", style = "normal" }
bold = { family = "Iosevka Nerd Font", style = "bold" }
italic = { family = "Iosevka Nerd Font", style = "italic" }
bold_italic = { family = "Iosevka Nerd Font", style = "bold_italic" }

[general]
# Import additional configuration files
import = ["~/dotfiles/alacritty/.config/alacritty/themes/everforest_dark.toml"]

[terminal]

# Colors
#[colors]
#primary = {
#background = "#1d1f21",
#foreground = "#c5c8c6",
#}

# Shell configuration
[terminal.shell]
program = "zsh"
args = ["-c", "tmux new-session -A -s $(uuidgen | tr -d '-')"]

# Key bindings
#[key_bindings]
# - { key = "V", mods = "Control|Shift", action = "Paste" }

# Mouse bindings
#[mouse_bindings]
# - { mouse = "Right", action = "ExpandSelection" }

# Hints
#[hints]
# - { regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+", hyperlinks = true, command = "xdg-open", post_processing = true, mouse = { enabled = true, mods = "None" }, binding = { key = "U", mods = "Control|Shift" } }

