---
# Windows-specific variables for development environment setup
# Equivalent to macOS macsible.yaml functionality for Windows

# Software inventory - tracks all managed software
chocolatey_packages:
  - powershell-core
  - starship
  - git
  - docker-desktop
  - python3
  - nodejs
  - golang
  - rustup.install
  - 7zip
  - unzip
  - curl
  - wget
  - vim
  - tmux
  - ranger
  - tree
  - zoxide

# Development Tools - Core Compilers and Assemblers
development_tools_chocolatey:
  # Essential compilers and toolchains
  - llvm
  - cmake
  - ninja
  - make
  - mingw
  - msys2
  - vcredist-all

  # Cross-platform assemblers
  - nasm
  - yasm

  # Build systems and tools
  - bazel
  - ccache
  - pkgconfiglite

  # Language toolchains
  - zig
  - crystal  # If available
  - dmd      # D language compiler

  # Development utilities
  - jq
  - grep
  - sed
  - gawk
  - which
  - procexp  # Process Explorer
  - sysinternals

chocolatey_gui_packages:
  - vscode
  - alacritty
  - firefox
  - googlechrome
  - postman
  - discord
  - slack
  - notion
  - obsidian
  - figma
  - zoom

# Windows Store apps (using winget)
winget_packages:
  - Microsoft.WindowsTerminal
  - Microsoft.PowerToys
  - Microsoft.VisualStudioCode
  - Git.Git

# Scoop packages (alternative package manager)
scoop_packages:
  - neovim
  - fzf
  - ripgrep
  - fd
  - bat
  - exa
  - zoxide

# Manual installations with verification
manual_installations:
  - name: "Windows Subsystem for Linux (WSL2)"
    check_command: "wsl --version"
    install_command: "wsl --install"
  - name: "Rust toolchain"
    check_command: "rustc --version"
    install_creates: "%USERPROFILE%\\.cargo\\bin\\rustc.exe"
  - name: "Node Version Manager (nvm-windows)"
    check_path: "%APPDATA%\\nvm\\nvm.exe"
  - name: "Zellij"
    check_command: "zellij --version"
    install_creates: "%USERPROFILE%\\.cargo\\bin\\zellij.exe"

# NPM global packages (same as macOS for consistency)
npm_global_packages:
  - "@angular/cli"
  - "create-react-app"
  - "typescript"
  - "ts-node"
  - "nodemon"
  - "pm2"
  - "yarn"
  - "pnpm"
  - "eslint"
  - "prettier"
  - "http-server"
  - "live-server"
  - "@modelcontextprotocol/server-brave-search"
  - "@modelcontextprotocol/server-puppeteer"
  - "firecrawl-mcp"

# Rust packages (cargo) - Enhanced with development tools
cargo_packages:
  - "lsd"
  - "starship"
  - "zellij"
  - "exa"
  - "bottom"
  - "tokei"
  - "hyperfine"
  - "ripgrep"
  - "fd-find"
  - "bat"
  - "zoxide"
  - "cargo-edit"
  - "cargo-watch"
  - "cargo-expand"
  - "cargo-audit"
  - "cargo-outdated"
  - "cargo-tree"

# Go packages (go install) - Essential Go development tools
go_packages:
  - "github.com/golangci/golangci-lint/cmd/golangci-lint@latest"
  - "golang.org/x/tools/cmd/goimports@latest"
  - "golang.org/x/tools/cmd/godoc@latest"
  - "github.com/go-delve/delve/cmd/dlv@latest"
  - "honnef.co/go/tools/cmd/staticcheck@latest"
  - "golang.org/x/tools/gopls@latest"
  - "github.com/fatih/gomodifytags@latest"
  - "github.com/josharian/impl@latest"

# Python development packages (pipx)
python_dev_packages:
  - "black"
  - "flake8"
  - "mypy"
  - "pytest"
  - "poetry"
  - "pipenv"
  - "virtualenv"
  - "cookiecutter"
  - "pre-commit"
  - "ansible-lint"
  - "community-ansible-dev-tools"

# Node.js development tools (global npm packages)
node_dev_packages:
  - "@typescript-eslint/eslint-plugin"
  - "@typescript-eslint/parser"
  - "webpack"
  - "webpack-cli"
  - "vite"
  - "esbuild"
  - "rollup"
  - "parcel"
  - "jest"
  - "mocha"
  - "cypress"

# Visual Studio Build Tools components
vs_build_tools:
  - "visualstudio2022buildtools"
  - "visualstudio2022-workload-vctools"
  - "windows-sdk-10-version-2004-all"

# PowerShell modules
powershell_modules:
  - PSReadLine
  - posh-git
  - Terminal-Icons
  - PSFzf
  - z

# Windows features to enable
windows_features:
  - Microsoft-Windows-Subsystem-Linux
  - VirtualMachinePlatform
  - Microsoft-Hyper-V-All
  - Containers-DisposableClientVM

# Environment variables
windows_environment_vars:
  - name: "EDITOR"
    value: "nvim"
    level: "user"
  - name: "BROWSER"
    value: "firefox"
    level: "user"
  - name: "TERMINAL"
    value: "alacritty"
    level: "user"

# Registry settings for development environment
registry_settings:
  - path: "HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced"
    name: "HideFileExt"
    value: 0
    type: "dword"
  - path: "HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced"
    name: "Hidden"
    value: 1
    type: "dword"

# Windows Defender exclusions for development
defender_exclusions:
  - "C:\\tools"
  - "C:\\ProgramData\\chocolatey"
  - "%USERPROFILE%\\.cargo"
  - "%USERPROFILE%\\AppData\\Roaming\\npm"
  - "%USERPROFILE%\\scoop"

# Development directories to create
development_directories:
  - "%USERPROFILE%\\dev"
  - "%USERPROFILE%\\projects"
  - "%USERPROFILE%\\tools"
  - "%USERPROFILE%\\.config"
