---
# macOS Enterprise Management Role Metadata

galaxy_info:
  role_name: macos_enterprise
  author: Dotsible Team
  description: Enterprise-friendly macOS configuration with MDM compatibility and desktop layout management
  company: Dotsible
  license: MIT
  min_ansible_version: 2.9
  
  platforms:
    - name: MacOSX
      versions:
        - 10.15
        - 11.0
        - 12.0
        - 13.0
        - 14.0
  
  galaxy_tags:
    - macos
    - enterprise
    - mdm
    - desktop
    - management
    - jamf
    - intune
    - configuration
    - plist
    - preferences

dependencies:
  - role: common
    when: common_role_enabled | default(true)
  - role: platform_specific/macos
    when: package_manager_role_enabled | default(true)
