;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;   To learn more about how to configure Polybar
;   go to https://github.com/polybar/polybar
;
;   The README contains a lot of information
;
;==========================================================

; Foraya theme (Ayu + Gruvbox + Everforest blend)
include-file = colors-foraya.ini

[bar/bit]
width = 100%
height = 28
radius = 1
border-color = #00000000
background = ${colors.background}
foreground = ${colors.foreground}
line-size = 1
padding-left = 1
padding-right = 1
module-margin = 0
modules-left = xworkspaces xwindow
modules-center = text5 text3 text1 date text2 text4 text6
modules-right = pulseaudio sep memory sep cpu sep network sep ssh-in sep ssh-out sep tray
enable-ipc = true
wm-restack = i3

# Fonts configuration - Primary (Size 8)
font-0 = "JetBrainsMonoNL Nerd Font:style=Regular:size=8;2"
font-1 = "JetBrainsMonoNL Nerd Font:style=Bold:size=8;2"
font-2 = "JetBrainsMonoNL Nerd Font:style=Italic:size=8;2"
font-3 = "JetBrainsMonoNL Nerd Font:style=Bold Italic:size=8;2"
font-4 = "JetBrainsMonoNL Nerd Font:style=ExtraLight:size=8;2"
font-5 = "JetBrainsMonoNL Nerd Font:style=Light:size=8;2"
font-6 = "JetBrainsMonoNL Nerd Font:style=Medium:size=8;2"
font-7 = "Font Awesome 5 Free:style=Regular:size=8;2"
font-8 = "Font Awesome 5 Free:style=Solid:size=8;2"
font-9 = "Font Awesome 5 Brands:style=Regular:size=8;2"

# Fonts configuration - Fallback (Other Sizes)
font-10 = "JetBrainsMonoNL Nerd Font:style=Regular:size=10;2"
font-11 = "JetBrainsMonoNL Nerd Font:style=Bold:size=10;2"
font-12 = "JetBrainsMonoNL Nerd Font:style=Italic:size=10;2"
font-13 = "JetBrainsMonoNL Nerd Font:style=Bold Italic:size=10;2"
font-14 = "JetBrainsMonoNL Nerd Font:style=ExtraLight:size=10;2"
font-15 = "JetBrainsMonoNL Nerd Font:style=Light:size=10;2"
font-16 = "JetBrainsMonoNL Nerd Font:style=Medium:size=10;2"
font-17 = "Font Awesome 5 Free:style=Regular:size=10;2"
font-18 = "Font Awesome 5 Free:style=Solid:size=10;2"
font-19 = "Font Awesome 5 Brands:style=Regular:size=10;2"

font-20 = "JetBrainsMonoNL Nerd Font:style=Regular:size=12;2"
font-21 = "JetBrainsMonoNL Nerd Font:style=Bold:size=12;2"
font-22 = "JetBrainsMonoNL Nerd Font:style=Italic:size=12;2"
font-23 = "JetBrainsMonoNL Nerd Font:style=Bold Italic:size=12;2"
font-24 = "JetBrainsMonoNL Nerd Font:style=ExtraLight:size=12;2"
font-25 = "JetBrainsMonoNL Nerd Font:style=Light:size=12;2"
font-26 = "JetBrainsMonoNL Nerd Font:style=Medium:size=12;2"
font-27 = "Font Awesome 5 Free:style=Regular:size=12;2"
font-28 = "Font Awesome 5 Free:style=Solid:size=12;2"
font-29 = "Font Awesome 5 Brands:style=Regular:size=12;2"

# Use specific fonts for modules or elements
[module/xworkspaces]
type = internal/xworkspaces
pin-workspaces = true
label-active = %name%
label-active-foreground = ${colors.green}
label-active-padding = 1
label-occupied = %name%
label-occupied-foreground = ${colors.inactive}
label-occupied-padding = 1
label-urgent = %name%
label-urgent-background = ${colors.alert}
label-urgent-padding = 1
label-empty = %name%
label-empty-foreground = ${colors.disabled}
label-empty-padding = 1

[module/xwindow]
type = internal/xwindow
label = %title:0:50%
label-padding = 2
label-foreground = ${colors.foreground-alt}

[module/tray]
type = internal/tray
tray-padding = 4px
tray-foreground = ${colors.foreground}

[module/pulseaudio]
type = internal/pulseaudio
format-volume-prefix = " "
format-volume-prefix-foreground = ${colors.aqua}
format-volume = <label-volume>
label-volume = %percentage%%
label-volume-padding-left = 1
label-muted = muted
label-muted-foreground = ${colors.disabled}
label-font = 21

[module/memory]
type = internal/memory
interval = 2
format-prefix = "󰍛 "
format-prefix-foreground = ${colors.pink}
label = %percentage_used:2%%

[module/system-usb-mount]
type = custom/script
exec = ~/.config/polybar/scripts/polybar-scripts/system-usb-mount/system-usb-mount.sh
interval = 5
click-left = ~/polybar-scripts/system-usb-mount.sh --mount &
click-right = ~/polybar-scripts/system-usb-mount.sh --unmount &

[module/backlight]
type = internal/backlight
card = amdgpu_bl0
use-actual-brightness = true
enable-scroll = true
format = <label>
format-prefix = "󰃠  "
format-prefix-foreground = ${colors.yellow}
label = %percentage%%
label-padding-right = ${padding.modules}
label-font = 5

[module/cpu]
type = internal/cpu
interval = 2
format-prefix = " "
format-prefix-foreground = ${colors.green}
label = %percentage:2%%

[module/network]
type = custom/script
exec = ~/.config/scripts/network/internet.sh
interval = 10
tail = true
format-foreground = ${colors.blue}
label-font = 1

[module/ssh-in]
type = custom/script
exec = ~/.config/scripts/ssh-in/ssh-in.sh
interval = 5
click-left = ~/.config/scripts/ssh-in/ssh-in.sh --details &
format-foreground = ${colors.aqua}
label-font = 1

[module/ssh-out]
type = custom/script
exec = ~/.config/scripts/ssh-out/ssh-out.sh
interval = 5
click-left = ~/.config/scripts/ssh-out/ssh-out.sh --details &
format-foreground = ${colors.orange}
label-font = 1

[module/text1]
type = custom/text
module-margin-left = 0
module-margin-right = 0
format = ""
format-foreground = ${gradient.color-1}
format-background = ${gradient.color-2}
label-font = 1

[module/text2]
type = custom/text
module-margin-left = 0
module-margin-right = 0
format = ""
format-foreground = ${gradient.color-1}
format-background = ${gradient.color-2}
label-font = 1

[module/text3]
type = custom/text
module-margin-left = 0
module-margin-right = 0
format = ""
format-foreground = ${gradient.color-2}
format-background = ${gradient.color-3}
label-font = 1

[module/text4]
type = custom/text
module-margin-left = 0
module-margin-right = 0
format = ""
format-foreground = ${gradient.color-2}
format-background = ${gradient.color-3}
label-font = 1

[module/text5]
type = custom/text
module-margin-left = 0
module-margin-right = 0
format = ""
format-foreground = ${gradient.color-3}
label-font = 1

[module/text6]
type = custom/text
module-margin-left = 0
module-margin-right = 0
format = ""
format-foreground = ${gradient.color-3}
label-font = 1

[module/date]
type = custom/script
exec = ~/.config/scripts/calendar/date-label.sh
interval = 1
click-left = ~/.config/scripts/calendar/calendar-popup.sh &
format-foreground = ${colors.foreground}
format-background = ${colors.background-alt}
format-font = 4

[module/sep]
type = custom/text
format = " 󰇙 "
format-foreground = ${colors.foreground-alt}
content-padding = 1
label-font = 21

[settings]
screenchange-reload = true
pseudo-transparency = true

# Padding setup
[padding]
modules = 20px

; vim:ft=dosini
