---
# Windows platform-specific handlers

- name: restart windows
  win_reboot:
    reboot_timeout: 600
    connect_timeout: 5
    test_command: whoami
  listen: "restart windows"

- name: refresh environment
  win_shell: |
    $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User")
    refreshenv
  listen: "refresh environment"

- name: restart chocolatey service
  win_service:
    name: chocolatey
    state: restarted
  listen: "restart chocolatey"

- name: update chocolatey
  win_chocolatey:
    name: chocolatey
    state: latest
  listen: "update chocolatey"

- name: refresh powershell profile
  win_shell: . $PROFILE
  listen: "refresh powershell profile"
  failed_when: false

- name: restart windows terminal
  win_shell: |
    Get-Process -Name "WindowsTerminal" -ErrorAction SilentlyContinue | Stop-Process -Force
    Start-Process "wt.exe"
  listen: "restart windows terminal"
  failed_when: false
