-- Foraya palette data (contrast=medium, accent=vivid)
-- Generated by theming/foraya/generate.py — do not hand-edit, edit
-- theming/foraya/palette.yml and regenerate instead.
-- Consumed by colors/foraya.lua; reusable by lualine/statusline plugins later.

return {
  meta = { name = "foraya", contrast = "medium", accent = "vivid" },
  bg = {
    base = "#0D1017",
    lift = "#10141C",
    panel = "#141821",
    popup = "#0F131A",
    line = "#161A24",
    gutter = "#1B1F29",
  },
  fg = {
    primary = "#EBDBB2",
    dim = "#5A6378",
  },
  neutral = {
    dim = "#7C6F64",
    mid = "#928374",
    bright = "#A89984",
  },
  cursor = {
    color = "#E6B450",
    text = "#0D1017",
  },
  selection = {
    background = "#543A48",
    foreground = "#EBDBB2",
  },
  accents = {
    red = "#FB4934",
    orange = "#FE8019",
    yellow = "#FABD2F",
    green = "#B8BB26",
    aqua = "#8EC07C",
    cyan = "#8EC07C",
    blue = "#83A598",
    purple = "#D3869B",
  },
  special = {
    gold = "#E6B450",
    hint = "#95E6CB",
    info = "#39BAE6",
    vcs = {
      added = "#70BF56",
      modified = "#73B8FF",
      removed = "#F26D78",
    },
  },
}
