-- Foraya palette data (contrast=hard, accent=muted)
-- Generated by theming/foraya/generate.py — do not hand-edit, edit
-- theming/foraya/palette.yml and regenerate instead.
-- Consumed by colors/foraya.lua; reusable by lualine/statusline plugins later.

return {
  meta = { name = "foraya", contrast = "hard", accent = "muted" },
  bg = {
    base = "#272E33",
    lift = "#2E383C",
    panel = "#374145",
    popup = "#272E33",
    line = "#374145",
    gutter = "#414B4F",
  },
  fg = {
    primary = "#D3C6AA",
    dim = "#5A6378",
  },
  neutral = {
    dim = "#7A8478",
    mid = "#859289",
    bright = "#9DA9A0",
  },
  cursor = {
    color = "#E6B450",
    text = "#272E33",
  },
  selection = {
    background = "#543A48",
    foreground = "#D3C6AA",
  },
  accents = {
    red = "#E67E80",
    orange = "#E69875",
    yellow = "#DBBC7F",
    green = "#A7C080",
    aqua = "#83C092",
    cyan = "#83C092",
    blue = "#7FBBB3",
    purple = "#D699B6",
  },
  special = {
    gold = "#E6B450",
    hint = "#95E6CB",
    info = "#39BAE6",
    vcs = {
      added = "#70BF56",
      modified = "#73B8FF",
      removed = "#F26D78",
    },
  },
}
