---
# Arch Linux-specific zoxide variables

# Installation method
zoxide_install_method: "pacman"
zoxide_package_name: "zoxide"

# Shell configuration
default_shell: "zsh"
shell_config_file: "{{ ansible_user_dir }}/.zshrc"

# Data directory
zoxide_data_dir: "{{ ansible_user_dir }}/.local/share"

# Arch Linux-specific configuration
archlinux_zoxide_config:
  use_pacman: true
  aur_alternative: "zoxide-bin"
  
# Shell integration priority (order of preference)
shell_priority:
  - zsh
  - bash
  - fish
