---
# macOS-specific variables extracted from macsible.yaml
# Software inventory - tracks all managed software
homebrew_packages:
  - powershell
  - starship
  - tmux
  - stow
  - ranger
  - sesh
  - git
  - docker
  - kubectl
  - python@3.11
  - neovim
  - node
  - npm
  - zsh
  - fzf
  - unzip
  - tree
  - zoxide

homebrew_casks:
  - visual-studio-code
  - iterm2
  - docker
  - alacritty
  - google-chrome
  - firefox
  - discord
  - slack
  - notion
  - postman
  - obsidian
  - figma
  - zoom

mac_app_store_apps:
  - name: "Xcode"
    path: "/Applications/Xcode.app"
  - name: "Keynote"
    path: "/Applications/Keynote.app"

manual_installations:
  - name: "Rust"
    check_command: "rustc --version"
    install_creates: "~/.cargo/bin/rustc"
  - name: "Node Version Manager (nvm)"
    check_path: "~/.nvm/nvm.sh"
  - name: "Go"
    check_command: "go version"
    version_pattern: "go1.21"
  - name: "Zellij"
    check_command: "zellij --version"
    install_creates: "/usr/local/bin/zellij"

npm_global_packages:
  - "@angular/cli"
  - "create-react-app"
  - "typescript"
  - "ts-node"
  - "nodemon"
  - "pm2"
  - "yarn"
  - "pnpm"
  - "eslint"
  - "prettier"
  - "http-server"
  - "live-server"
  - "@modelcontextprotocol/server-brave-search"
  - "@modelcontextprotocol/server-puppeteer"
  - "firecrawl-mcp"

# Rust packages (cargo)
cargo_packages:
  - "lsd"
  - "starship"
  - "zellij"
  - "exa"
  - "bottom"
  - "tokei"
  - "hyperfine"
  - "ripgrep"
  - "fd-find"
  - "bat"

# ZSH and Oh My Zsh configuration
zsh_packages:
  - zsh
  - fzf

# Oh My Zsh plugins to install via git clone
oh_my_zsh_plugins:
  - name: zsh-autosuggestions
    repo: https://github.com/zsh-users/zsh-autosuggestions
  - name: zsh-fzf-history-search
    repo: https://github.com/joshskidmore/zsh-fzf-history-search
  - name: zsh-syntax-highlighting
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
  - name: zsh-history-substring-search
    repo: https://github.com/zsh-users/zsh-history-substring-search

# FZF configuration
fzf_install_method: "homebrew"  # homebrew, git, or binary
