---
# macOS-specific variables extracted from macsible.yaml
# Software inventory - tracks all managed software
homebrew_packages:
  - powershell
  - starship
  - tmux
  - stow
  - ranger
  - sesh
  - git
  - docker
  - kubectl
  - python@3.11
  - neovim
  - node
  - npm
  - zsh
  - fzf
  - unzip
  - tree
  - zoxide

# Development Tools - Core Compilers and Assemblers
development_tools:
  # Essential compilers
  - gcc
  - llvm
  - clang-format
  - cmake
  - ninja
  - make
  - autoconf
  - automake
  - libtool
  - pkg-config

  # Cross-platform assemblers
  - nasm
  - yasm

  # Build systems and tools
  - meson
  - bazel
  - ccache

  # Language toolchains
  - rust
  - go
  - zig
  - crystal
  - nim
  - dmd  # D language compiler

  # Additional development utilities
  - gdb
  - lldb
  - valgrind
  - strace
  - htop
  - jq
  - curl
  - wget

homebrew_casks:
  - visual-studio-code
  - iterm2
  - docker
  - alacritty
  - google-chrome
  - firefox
  - discord
  - slack
  - notion
  - postman
  - obsidian
  - figma
  - zoom

mac_app_store_apps:
  - name: "Xcode"
    path: "/Applications/Xcode.app"
  - name: "Keynote"
    path: "/Applications/Keynote.app"

manual_installations:
  - name: "Rust"
    check_command: "rustc --version"
    install_creates: "~/.cargo/bin/rustc"
  - name: "Node Version Manager (nvm)"
    check_path: "~/.nvm/nvm.sh"
  - name: "Go"
    check_command: "go version"
    version_pattern: "go1.2[4-9]"
  - name: "Zellij"
    check_command: "zellij --version"
    install_creates: "/usr/local/bin/zellij"

npm_global_packages:
  - "@angular/cli"
  - "create-react-app"
  - "typescript"
  - "ts-node"
  - "nodemon"
  - "pm2"
  - "yarn"
  - "pnpm"
  - "eslint"
  - "prettier"
  - "http-server"
  - "live-server"
  - "@modelcontextprotocol/server-brave-search"
  - "@modelcontextprotocol/server-puppeteer"
  - "firecrawl-mcp"

# Rust packages (cargo) - Enhanced with development tools
cargo_packages:
  - "lsd"
  - "starship"
  - "zellij"
  - "exa"
  - "bottom"
  - "tokei"
  - "hyperfine"
  - "ripgrep"
  - "fd-find"
  - "bat"
  - "zoxide"
  - "cargo-edit"
  - "cargo-watch"
  - "cargo-expand"
  - "cargo-audit"
  - "cargo-outdated"
  - "cargo-tree"

# Go packages (go install) - Essential Go development tools
go_packages:
  - "github.com/golangci/golangci-lint/cmd/golangci-lint@latest"
  - "golang.org/x/tools/cmd/goimports@latest"
  - "golang.org/x/tools/cmd/godoc@latest"
  - "github.com/go-delve/delve/cmd/dlv@latest"
  - "honnef.co/go/tools/cmd/staticcheck@latest"
  - "golang.org/x/tools/gopls@latest"
  - "github.com/fatih/gomodifytags@latest"
  - "github.com/josharian/impl@latest"

# Python development packages (pipx)
python_dev_packages:
  - "black"
  - "flake8"
  - "mypy"
  - "pytest"
  - "poetry"
  - "pipenv"
  - "virtualenv"
  - "cookiecutter"
  - "pre-commit"
  - "ansible-lint"
  - "community-ansible-dev-tools"

# Node.js development tools (global npm packages)
node_dev_packages:
  - "@typescript-eslint/eslint-plugin"
  - "@typescript-eslint/parser"
  - "webpack"
  - "webpack-cli"
  - "vite"
  - "esbuild"
  - "rollup"
  - "parcel"
  - "jest"
  - "mocha"
  - "cypress"

# Cross-compilation toolchains
cross_compilation_tools:
  - "mingw-w64"
  - "arm-linux-gnueabihf-gcc"  # ARM cross-compiler
  - "aarch64-linux-gnu-gcc"    # ARM64 cross-compiler

# ZSH and Oh My Zsh configuration
zsh_packages:
  - zsh
  - fzf

# Oh My Zsh plugins to install via git clone
oh_my_zsh_plugins:
  - name: zsh-autosuggestions
    repo: https://github.com/zsh-users/zsh-autosuggestions
  - name: zsh-fzf-history-search
    repo: https://github.com/joshskidmore/zsh-fzf-history-search
  - name: zsh-syntax-highlighting
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
  - name: zsh-history-substring-search
    repo: https://github.com/zsh-users/zsh-history-substring-search

# FZF configuration
fzf_install_method: "homebrew"  # homebrew, git, or binary
