---
# Ubuntu/Debian-specific variables for development environment setup
# Equivalent to macOS macsible.yaml functionality for Ubuntu/Debian

# Software inventory - tracks all managed software
apt_packages:
  - build-essential
  - git
  - curl
  - wget
  - vim
  - neovim
  - tmux
  - zsh
  - alacritty
  - firefox
  - docker.io
  - docker-compose
  - python3
  - python3-pip
  - python3-venv
  - nodejs
  - npm
  - golang-go
  - rustc
  - cargo
  - ripgrep
  - fd-find
  - bat
  - fzf
  - ranger
  - htop
  - tree
  - unzip
  - zip
  - jq
  - software-properties-common
  - apt-transport-https
  - ca-certificates
  - gnupg
  - lsb-release

# Snap packages
snap_packages:
  - code
  - discord
  - slack
  - postman
  - go
  - node
  - obsidian
  - figma-linux
  - zoom-client

# Development packages - Enhanced with comprehensive toolchain
dev_packages:
  - gcc
  - g++
  - clang
  - llvm
  - cmake
  - make
  - ninja-build
  - meson
  - autoconf
  - automake
  - libtool
  - pkg-config
  - libssl-dev
  - sqlite3
  - libsqlite3-dev
  - postgresql
  - postgresql-contrib
  - redis-server
  - default-jdk

# Cross-platform assemblers and low-level tools
assembler_packages:
  - nasm
  - yasm
  - gdb
  - lldb
  - valgrind
  - strace
  - linux-tools-generic  # includes perf
  - binutils
  - objdump

# Build systems and development utilities
build_tools:
  - ccache
  - distcc
  - shellcheck
  - jq
  - yq

# Language toolchains (via external sources)
language_packages:
  - golang-go
  - rustc
  - cargo

# Cross-compilation toolchains
cross_compilation_packages:
  - gcc-arm-linux-gnueabihf
  - gcc-aarch64-linux-gnu
  - gcc-mingw-w64

# Window manager packages (for Ubuntu desktop)
wm_packages:
  - i3-wm
  - i3status
  - i3lock
  - sway
  - waybar
  - wofi
  - rofi
  - dmenu
  - polybar
  - picom
  - dunst
  - feh
  - grim
  - slurp
  - wl-clipboard

# Fonts
font_packages:
  - fonts-jetbrains-mono
  - fonts-font-awesome
  - fonts-noto
  - fonts-noto-color-emoji
  - fonts-powerline
  - fonts-hack

# System utilities
system_packages:
  - network-manager
  - bluetooth
  - bluez
  - pulseaudio
  - pulseaudio-module-bluetooth
  - pavucontrol
  - brightnessctl
  - acpi
  - upower
  - flatpak
  - snapd

# PPAs to add
ubuntu_ppas:
  - ppa:neovim-ppa/unstable
  - ppa:git-core/ppa
  - ppa:deadsnakes/ppa

# External repositories
external_repos:
  - name: "Docker"
    key_url: "https://download.docker.com/linux/ubuntu/gpg"
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
  - name: "NodeJS"
    key_url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
    repo: "deb https://deb.nodesource.com/node_18.x {{ ansible_distribution_release }} main"

# NPM global packages (same as macOS for consistency)
npm_global_packages:
  - "@angular/cli"
  - "create-react-app"
  - "typescript"
  - "ts-node"
  - "nodemon"
  - "pm2"
  - "yarn"
  - "pnpm"
  - "eslint"
  - "prettier"
  - "http-server"
  - "live-server"
  - "@modelcontextprotocol/server-brave-search"
  - "@modelcontextprotocol/server-puppeteer"
  - "firecrawl-mcp"

# ZSH and Oh My Zsh configuration
zsh_packages:
  - zsh
  - fzf

# Oh My Zsh plugins to install via git clone
oh_my_zsh_plugins:
  - name: zsh-autosuggestions
    repo: https://github.com/zsh-users/zsh-autosuggestions
  - name: zsh-fzf-history-search
    repo: https://github.com/joshskidmore/zsh-fzf-history-search
  - name: zsh-syntax-highlighting
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
  - name: zsh-history-substring-search
    repo: https://github.com/zsh-users/zsh-history-substring-search

# FZF configuration
fzf_install_method: "apt"  # apt, git, or binary

# Python packages
python_packages:
  - "pynvim"
  - "black"
  - "isort"
  - "flake8"
  - "mypy"
  - "pytest"
  - "requests"
  - "beautifulsoup4"
  - "pandas"
  - "numpy"
  - "jupyter"

# Rust packages (cargo) - Enhanced with development tools
cargo_packages:
  - "lsd"
  - "starship"
  - "zellij"
  - "exa"
  - "bottom"
  - "tokei"
  - "hyperfine"
  - "ripgrep"
  - "fd-find"
  - "bat"
  - "zoxide"
  - "cargo-edit"
  - "cargo-watch"
  - "cargo-expand"
  - "cargo-audit"
  - "cargo-outdated"
  - "cargo-tree"

# Go packages (go install) - Essential Go development tools
go_packages:
  - "github.com/golangci/golangci-lint/cmd/golangci-lint@latest"
  - "golang.org/x/tools/cmd/goimports@latest"
  - "golang.org/x/tools/cmd/godoc@latest"
  - "github.com/go-delve/delve/cmd/dlv@latest"
  - "honnef.co/go/tools/cmd/staticcheck@latest"
  - "golang.org/x/tools/gopls@latest"
  - "github.com/fatih/gomodifytags@latest"
  - "github.com/josharian/impl@latest"



# Python development packages (pipx)
python_dev_packages:
  - "black"
  - "flake8"
  - "mypy"
  - "pytest"
  - "poetry"
  - "pipenv"
  - "virtualenv"
  - "cookiecutter"
  - "pre-commit"
  - "ansible-lint"
  - "community-ansible-dev-tools"

# Node.js development tools (global npm packages)
node_dev_packages:
  - "@typescript-eslint/eslint-plugin"
  - "@typescript-eslint/parser"
  - "webpack"
  - "webpack-cli"
  - "vite"
  - "esbuild"
  - "rollup"
  - "parcel"
  - "jest"
  - "mocha"
  - "cypress"

# External language installations (manual)
external_language_tools:
  - name: "Zig"
    check_command: "zig version"
    install_url: "https://ziglang.org/download/"
  - name: "Crystal"
    check_command: "crystal --version"
    install_url: "https://crystal-lang.org/install/"
  - name: "Nim"
    check_command: "nim --version"
    install_url: "https://nim-lang.org/install.html"

# Services to enable
systemd_services:
  - "docker"
  - "bluetooth"
  - "NetworkManager"

# Development directories to create
development_directories:
  - "{{ ansible_user_dir }}/dev"
  - "{{ ansible_user_dir }}/projects"
  - "{{ ansible_user_dir }}/src"
  - "{{ ansible_user_dir }}/.local/bin"

# Environment variables
ubuntu_environment_vars:
  - name: "EDITOR"
    value: "nvim"
  - name: "BROWSER"
    value: "firefox"
  - name: "TERMINAL"
    value: "alacritty"
  - name: "PATH"
    value: "{{ ansible_user_dir }}/.local/bin:{{ ansible_user_dir }}/.cargo/bin:{{ ansible_user_dir }}/go/bin:$PATH"

# Flatpak applications
flatpak_packages:
  - "com.visualstudio.code"
  - "org.mozilla.firefox"
  - "com.google.Chrome"
  - "com.discordapp.Discord"
  - "com.slack.Slack"
  - "md.obsidian.Obsidian"
  - "io.github.Figma_Linux.figma_linux"
  - "us.zoom.Zoom"
